buildVariable: true
familyName: Noto Sans
googleFonts: true
sources:
- NotoSans.glyphspackage
- NotoSans-Italic.glyphspackage
includeSubsets:
- from: Noto Sans Devanagari
  layoutHandling: closure
  ranges:
    - start: 0x900
      end: 0x97F
